#include "vm.h"
CF_BEGIN

fr_Obj sys_Bool_fromStr_f(fr_Env env, fr_Obj s, fr_Bool checked);
void sys_Bool_privateMake_f(fr_Env env, fr_Bool self);
fr_Bool sys_Bool_equals_f(fr_Env env, fr_Bool self, fr_Obj obj);
fr_Int sys_Bool_hash_f(fr_Env env, fr_Bool self);
fr_Obj sys_Bool_toStr_f(fr_Env env, fr_Bool self);
fr_Obj sys_Bool_toLocale_f(fr_Env env, fr_Bool self);
fr_Bool sys_Bool_not_f(fr_Env env, fr_Bool self);
fr_Bool sys_Bool_and_f(fr_Env env, fr_Bool self, fr_Bool b);
fr_Bool sys_Bool_or_f(fr_Env env, fr_Bool self, fr_Bool b);
fr_Bool sys_Bool_xor_f(fr_Env env, fr_Bool self, fr_Bool b);
fr_Obj sys_Bool_toCode_f(fr_Env env, fr_Bool self);
void sys_Err_make_f(fr_Env env, fr_Obj self, fr_Obj msg, fr_Obj cause);
fr_Obj sys_Err_msg_f(fr_Env env, fr_Obj self);
fr_Obj sys_Err_cause_f(fr_Env env, fr_Obj self);
fr_Obj sys_Err_traceToStr_f(fr_Env env, fr_Obj self);
fr_Obj sys_Err_toStr_f(fr_Env env, fr_Obj self);
void sys_Num_make_f(fr_Env env, fr_Obj self);
fr_Int sys_Num_toInt_f(fr_Env env, fr_Obj self);
fr_Float sys_Num_toFloat_f(fr_Env env, fr_Obj self);
fr_Obj sys_Num_localeDecimal_f(fr_Env env);
fr_Obj sys_Num_localeGrouping_f(fr_Env env);
fr_Obj sys_Num_localeMinus_f(fr_Env env);
fr_Obj sys_Num_localePercent_f(fr_Env env);
fr_Obj sys_Num_localePosInf_f(fr_Env env);
fr_Obj sys_Num_localeNegInf_f(fr_Env env);
fr_Obj sys_Num_localeNaN_f(fr_Env env);
fr_Float sys_Float_makeBits_f(fr_Env env, fr_Int bits);
fr_Float sys_Float_makeBits32_f(fr_Env env, fr_Int bits);
fr_Obj sys_Float_fromStr_f(fr_Env env, fr_Obj s, fr_Bool checked);
fr_Float sys_Float_random_f(fr_Env env);
fr_Obj sys_Float_privateMake_f(fr_Env env);
fr_Bool sys_Float_equals_f(fr_Env env, fr_Float self, fr_Obj obj);
fr_Bool sys_Float_approx_f(fr_Env env, fr_Float self, fr_Float r, fr_Obj tolerance);
fr_Int sys_Float_compare_f(fr_Env env, fr_Float self, fr_Obj obj);
fr_Bool sys_Float_isNaN_f(fr_Env env, fr_Float self);
fr_Int sys_Float_hash_f(fr_Env env, fr_Float self);
fr_Float sys_Float_negate_f(fr_Env env, fr_Float self);
fr_Float sys_Float_increment_f(fr_Env env, fr_Float self);
fr_Float sys_Float_decrement_f(fr_Env env, fr_Float self);
fr_Float sys_Float_mult_f(fr_Env env, fr_Float self, fr_Float b);
fr_Float sys_Float_multInt_f(fr_Env env, fr_Float self, fr_Int b);
fr_Float sys_Float_div_f(fr_Env env, fr_Float self, fr_Float b);
fr_Float sys_Float_divInt_f(fr_Env env, fr_Float self, fr_Int b);
fr_Float sys_Float_mod_f(fr_Env env, fr_Float self, fr_Float b);
fr_Float sys_Float_modInt_f(fr_Env env, fr_Float self, fr_Int b);
fr_Float sys_Float_plus_f(fr_Env env, fr_Float self, fr_Float b);
fr_Float sys_Float_plusInt_f(fr_Env env, fr_Float self, fr_Int b);
fr_Float sys_Float_minus_f(fr_Env env, fr_Float self, fr_Float b);
fr_Float sys_Float_minusInt_f(fr_Env env, fr_Float self, fr_Int b);
fr_Float sys_Float_abs_f(fr_Env env, fr_Float self);
fr_Float sys_Float_min_f(fr_Env env, fr_Float self, fr_Float that);
fr_Float sys_Float_max_f(fr_Env env, fr_Float self, fr_Float that);
fr_Float sys_Float_ceil_f(fr_Env env, fr_Float self);
fr_Float sys_Float_floor_f(fr_Env env, fr_Float self);
fr_Float sys_Float_round_f(fr_Env env, fr_Float self);
fr_Float sys_Float_exp_f(fr_Env env, fr_Float self);
fr_Float sys_Float_log_f(fr_Env env, fr_Float self);
fr_Float sys_Float_log10_f(fr_Env env, fr_Float self);
fr_Float sys_Float_pow_f(fr_Env env, fr_Float self, fr_Float pow);
fr_Float sys_Float_sqrt_f(fr_Env env, fr_Float self);
fr_Float sys_Float_acos_f(fr_Env env, fr_Float self);
fr_Float sys_Float_asin_f(fr_Env env, fr_Float self);
fr_Float sys_Float_atan_f(fr_Env env, fr_Float self);
fr_Float sys_Float_atan2_f(fr_Env env, fr_Float y, fr_Float x);
fr_Float sys_Float_cos_f(fr_Env env, fr_Float self);
fr_Float sys_Float_cosh_f(fr_Env env, fr_Float self);
fr_Float sys_Float_sin_f(fr_Env env, fr_Float self);
fr_Float sys_Float_sinh_f(fr_Env env, fr_Float self);
fr_Float sys_Float_tan_f(fr_Env env, fr_Float self);
fr_Float sys_Float_tanh_f(fr_Env env, fr_Float self);
fr_Float sys_Float_toDegrees_f(fr_Env env, fr_Float self);
fr_Float sys_Float_toRadians_f(fr_Env env, fr_Float self);
fr_Int sys_Float_bits_f(fr_Env env, fr_Float self);
fr_Int sys_Float_bits32_f(fr_Env env, fr_Float self);
fr_Obj sys_Float_toStr_f(fr_Env env, fr_Float self);
fr_Obj sys_Float_toCode_f(fr_Env env, fr_Float self);
void sys_Float_make_f(fr_Env env, fr_Float self);
fr_Obj sys_Int_fromStr_f(fr_Env env, fr_Obj s, fr_Int radix, fr_Bool checked);
fr_Int sys_Int_random_f(fr_Env env, fr_Obj r);
fr_Obj sys_Int_privateMake_f(fr_Env env);
fr_Bool sys_Int_equals_f(fr_Env env, fr_Int self, fr_Obj obj);
fr_Int sys_Int_compare_f(fr_Env env, fr_Int self, fr_Obj obj);
fr_Int sys_Int_hash_f(fr_Env env, fr_Int self);
fr_Int sys_Int_negate_f(fr_Env env, fr_Int self);
fr_Int sys_Int_increment_f(fr_Env env, fr_Int self);
fr_Int sys_Int_decrement_f(fr_Env env, fr_Int self);
fr_Int sys_Int_mult_f(fr_Env env, fr_Int self, fr_Int b);
fr_Float sys_Int_multFloat_f(fr_Env env, fr_Int self, fr_Float b);
fr_Int sys_Int_div_f(fr_Env env, fr_Int self, fr_Int b);
fr_Float sys_Int_divFloat_f(fr_Env env, fr_Int self, fr_Float b);
fr_Int sys_Int_mod_f(fr_Env env, fr_Int self, fr_Int b);
fr_Float sys_Int_modFloat_f(fr_Env env, fr_Int self, fr_Float b);
fr_Int sys_Int_plus_f(fr_Env env, fr_Int self, fr_Int b);
fr_Float sys_Int_plusFloat_f(fr_Env env, fr_Int self, fr_Float b);
fr_Int sys_Int_minus_f(fr_Env env, fr_Int self, fr_Int b);
fr_Float sys_Int_minusFloat_f(fr_Env env, fr_Int self, fr_Float b);
fr_Int sys_Int_not_f(fr_Env env, fr_Int self);
fr_Int sys_Int_and_f(fr_Env env, fr_Int self, fr_Int b);
fr_Int sys_Int_or_f(fr_Env env, fr_Int self, fr_Int b);
fr_Int sys_Int_xor_f(fr_Env env, fr_Int self, fr_Int b);
fr_Int sys_Int_shiftl_f(fr_Env env, fr_Int self, fr_Int b);
fr_Int sys_Int_shiftr_f(fr_Env env, fr_Int self, fr_Int b);
fr_Int sys_Int_abs_f(fr_Env env, fr_Int self);
fr_Int sys_Int_min_f(fr_Env env, fr_Int self, fr_Int that);
fr_Int sys_Int_max_f(fr_Env env, fr_Int self, fr_Int that);
fr_Int sys_Int_pow_f(fr_Env env, fr_Int self, fr_Int pow);
fr_Bool sys_Int_isEven_f(fr_Env env, fr_Int self);
fr_Bool sys_Int_isOdd_f(fr_Env env, fr_Int self);
fr_Bool sys_Int_isSpace_f(fr_Env env, fr_Int self);
fr_Bool sys_Int_isAlpha_f(fr_Env env, fr_Int self);
fr_Bool sys_Int_isAlphaNum_f(fr_Env env, fr_Int self);
fr_Bool sys_Int_isUpper_f(fr_Env env, fr_Int self);
fr_Bool sys_Int_isLower_f(fr_Env env, fr_Int self);
fr_Int sys_Int_upper_f(fr_Env env, fr_Int self);
fr_Int sys_Int_lower_f(fr_Env env, fr_Int self);
fr_Bool sys_Int_isDigit_f(fr_Env env, fr_Int self, fr_Int radix);
fr_Obj sys_Int_toDigit_f(fr_Env env, fr_Int self, fr_Int radix);
fr_Obj sys_Int_fromDigit_f(fr_Env env, fr_Int self, fr_Int radix);
fr_Bool sys_Int_equalsIgnoreCase_f(fr_Env env, fr_Int self, fr_Int ch);
fr_Bool sys_Int_localeIsUpper_f(fr_Env env, fr_Int self);
fr_Bool sys_Int_localeIsLower_f(fr_Env env, fr_Int self);
fr_Int sys_Int_localeUpper_f(fr_Env env, fr_Int self);
fr_Int sys_Int_localeLower_f(fr_Env env, fr_Int self);
fr_Obj sys_Int_toStr_f(fr_Env env, fr_Int self);
fr_Obj sys_Int_toHex_f(fr_Env env, fr_Int self, fr_Obj width);
fr_Obj sys_Int_toRadix_f(fr_Env env, fr_Int self, fr_Int radix, fr_Obj width);
fr_Obj sys_Int_toChar_f(fr_Env env, fr_Int self);
fr_Obj sys_Int_toCode_f(fr_Env env, fr_Int self, fr_Int base);
void sys_Int_times_f(fr_Env env, fr_Int self, fr_Obj c);
void sys_Int_make_f(fr_Env env, fr_Int self);
void sys_Obj_make_f(fr_Env env, fr_Obj self);
fr_Bool sys_Obj_equals_f(fr_Env env, fr_Obj self, fr_Obj that);
fr_Int sys_Obj_compare_f(fr_Env env, fr_Obj self, fr_Obj that);
fr_Int sys_Obj_hash_f(fr_Env env, fr_Obj self);
fr_Obj sys_Obj_toStr_f(fr_Env env, fr_Obj self);
fr_Obj sys_Obj_trap_f(fr_Env env, fr_Obj self, fr_Obj name, fr_Obj args);
fr_Obj sys_Obj_with_f(fr_Env env, fr_Obj self, fr_Obj f);
fr_Bool sys_Obj_isImmutable_f(fr_Env env, fr_Obj self);
fr_Obj sys_Obj_toImmutable_f(fr_Env env, fr_Obj self);
fr_Obj sys_Obj_typeof_f(fr_Env env, fr_Obj self);
void sys_Obj_finalize_f(fr_Env env, fr_Obj self);
void sys_Obj_echo_f(fr_Env env, fr_Obj x);
void sys_Str_privateMake_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_fromChars_f(fr_Env env, fr_Obj chars);
fr_Bool sys_Str_equals_f(fr_Env env, fr_Obj self, fr_Obj obj);
fr_Bool sys_Str_equalsIgnoreCase_f(fr_Env env, fr_Obj self, fr_Obj s);
fr_Int sys_Str_compare_f(fr_Env env, fr_Obj self, fr_Obj obj);
fr_Int sys_Str_compareIgnoreCase_f(fr_Env env, fr_Obj self, fr_Obj s);
fr_Int sys_Str_hash_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_toStr_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_toLocale_f(fr_Env env, fr_Obj self);
fr_Bool sys_Str_isEmpty_f(fr_Env env, fr_Obj self);
fr_Int sys_Str_size_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_intern_f(fr_Env env, fr_Obj self);
fr_Bool sys_Str_startsWith_f(fr_Env env, fr_Obj self, fr_Obj s);
fr_Bool sys_Str_endsWith_f(fr_Env env, fr_Obj self, fr_Obj s);
fr_Obj sys_Str_index_f(fr_Env env, fr_Obj self, fr_Obj s, fr_Int offset);
fr_Obj sys_Str_indexr_f(fr_Env env, fr_Obj self, fr_Obj s, fr_Int offset);
fr_Obj sys_Str_indexIgnoreCase_f(fr_Env env, fr_Obj self, fr_Obj s, fr_Int offset);
fr_Obj sys_Str_indexrIgnoreCase_f(fr_Env env, fr_Obj self, fr_Obj s, fr_Int offset);
fr_Bool sys_Str_contains_f(fr_Env env, fr_Obj self, fr_Obj s);
fr_Bool sys_Str_containsChar_f(fr_Env env, fr_Obj self, fr_Int ch);
fr_Int sys_Str_get_f(fr_Env env, fr_Obj self, fr_Int index);
fr_Int sys_Str_getSafe_f(fr_Env env, fr_Obj self, fr_Int index, fr_Int def);
fr_Obj sys_Str_getRange_f(fr_Env env, fr_Obj self, fr_Obj range);
fr_Obj sys_Str_plus_f(fr_Env env, fr_Obj self, fr_Obj obj);
fr_Obj sys_Str_chars_f(fr_Env env, fr_Obj self);
void sys_Str_each_f(fr_Env env, fr_Obj self, fr_Obj c);
void sys_Str_eachr_f(fr_Env env, fr_Obj self, fr_Obj c);
fr_Bool sys_Str_any_f(fr_Env env, fr_Obj self, fr_Obj c);
fr_Bool sys_Str_all_f(fr_Env env, fr_Obj self, fr_Obj c);
fr_Obj sys_Str_spaces_f(fr_Env env, fr_Int n);
fr_Obj sys_Str_lower_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_upper_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_capitalize_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_decapitalize_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_toDisplayName_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_fromDisplayName_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_justl_f(fr_Env env, fr_Obj self, fr_Int width);
fr_Obj sys_Str_justr_f(fr_Env env, fr_Obj self, fr_Int width);
fr_Obj sys_Str_padl_f(fr_Env env, fr_Obj self, fr_Int width, fr_Int char_);
fr_Obj sys_Str_padr_f(fr_Env env, fr_Obj self, fr_Int width, fr_Int char_);
fr_Obj sys_Str_reverse_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_trim_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_trimToNull_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_trimStart_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_trimEnd_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_split_f(fr_Env env, fr_Obj self, fr_Obj separator, fr_Bool trim);
fr_Obj sys_Str_splitLines_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_replace_f(fr_Env env, fr_Obj self, fr_Obj from, fr_Obj to);
fr_Int sys_Str_numNewlines_f(fr_Env env, fr_Obj self);
fr_Bool sys_Str_isAscii_f(fr_Env env, fr_Obj self);
fr_Bool sys_Str_isSpace_f(fr_Env env, fr_Obj self);
fr_Bool sys_Str_isUpper_f(fr_Env env, fr_Obj self);
fr_Bool sys_Str_isLower_f(fr_Env env, fr_Obj self);
fr_Bool sys_Str_isAlpha_f(fr_Env env, fr_Obj self);
fr_Bool sys_Str_isAlphaNum_f(fr_Env env, fr_Obj self);
fr_Int sys_Str_localeCompare_f(fr_Env env, fr_Obj self, fr_Obj s);
fr_Obj sys_Str_localeLower_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_localeUpper_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_localeCapitalize_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_localeDecapitalize_f(fr_Env env, fr_Obj self);
fr_Obj sys_Str_toBool_f(fr_Env env, fr_Obj self, fr_Bool checked);
fr_Obj sys_Str_toInt_f(fr_Env env, fr_Obj self, fr_Int radix, fr_Bool checked);
fr_Obj sys_Str_toFloat_f(fr_Env env, fr_Obj self, fr_Bool checked);
fr_Obj sys_Str_toCode_f(fr_Env env, fr_Obj self, fr_Obj quote, fr_Bool escapeUnicode);
fr_Obj sys_Str_toXml_f(fr_Env env, fr_Obj self);
void sys_Str_finalize_f(fr_Env env, fr_Obj self);
void sys_Str_static__init_f(fr_Env env);
void sys_StrBuf_make_f(fr_Env env, fr_Obj self, fr_Int capacity);
fr_Bool sys_StrBuf_isEmpty_f(fr_Env env, fr_Obj self);
fr_Int sys_StrBuf_size_f(fr_Env env, fr_Obj self);
fr_Int sys_StrBuf_capacity_f(fr_Env env, fr_Obj self);
void sys_StrBuf_capacity__f(fr_Env env, fr_Obj self, fr_Int it);
fr_Int sys_StrBuf_get_f(fr_Env env, fr_Obj self, fr_Int index);
fr_Obj sys_StrBuf_getRange_f(fr_Env env, fr_Obj self, fr_Obj range);
fr_Obj sys_StrBuf_set_f(fr_Env env, fr_Obj self, fr_Int index, fr_Int ch);
fr_Obj sys_StrBuf_add_f(fr_Env env, fr_Obj self, fr_Obj x);
fr_Obj sys_StrBuf_addChar_f(fr_Env env, fr_Obj self, fr_Int ch);
fr_Obj sys_StrBuf_join_f(fr_Env env, fr_Obj self, fr_Obj x, fr_Obj sep);
fr_Obj sys_StrBuf_insert_f(fr_Env env, fr_Obj self, fr_Int index, fr_Obj x);
fr_Obj sys_StrBuf_remove_f(fr_Env env, fr_Obj self, fr_Int index);
fr_Obj sys_StrBuf_removeRange_f(fr_Env env, fr_Obj self, fr_Obj r);
fr_Obj sys_StrBuf_replaceRange_f(fr_Env env, fr_Obj self, fr_Obj r, fr_Obj str);
fr_Obj sys_StrBuf_clear_f(fr_Env env, fr_Obj self);
fr_Obj sys_StrBuf_toStr_f(fr_Env env, fr_Obj self);
void sys_StrBuf_finalize_f(fr_Env env, fr_Obj self);
void sys_This_make_f(fr_Env env, fr_Obj self);
void sys_Void_make_f(fr_Env env, fr_Obj self);
void sys_ByteArray_make_f(fr_Env env, fr_Obj self, fr_Int size);
fr_Int sys_ByteArray_get_f(fr_Env env, fr_Obj self, fr_Int pos);
fr_Int sys_ByteArray_set_f(fr_Env env, fr_Obj self, fr_Int pos, fr_Int val);
fr_Int sys_ByteArray_size_f(fr_Env env, fr_Obj self);
fr_Bool sys_ByteArray_realloc_f(fr_Env env, fr_Obj self, fr_Int newSize);
fr_Obj sys_ByteArray_copyFrom_f(fr_Env env, fr_Obj self, fr_Obj that, fr_Int thatOffset, fr_Int thisOffset, fr_Int length);
void sys_ByteArray_finalize_f(fr_Env env, fr_Obj self);
void sys_IntArray_make_f(fr_Env env, fr_Obj self, fr_Int size);
fr_Int sys_IntArray_get_f(fr_Env env, fr_Obj self, fr_Int pos);
fr_Int sys_IntArray_set_f(fr_Env env, fr_Obj self, fr_Int pos, fr_Int val);
fr_Int sys_IntArray_size_f(fr_Env env, fr_Obj self);
fr_Bool sys_IntArray_realloc_f(fr_Env env, fr_Obj self, fr_Int newSize);
fr_Obj sys_IntArray_copyFrom_f(fr_Env env, fr_Obj self, fr_Obj that, fr_Int thatOffset, fr_Int thisOffset, fr_Int length);
void sys_IntArray_finalize_f(fr_Env env, fr_Obj self);
void sys_ObjArray_make_f(fr_Env env, fr_Obj self, fr_Int size);
fr_Obj sys_ObjArray_get_f(fr_Env env, fr_Obj self, fr_Int pos);
void sys_ObjArray_set_f(fr_Env env, fr_Obj self, fr_Int pos, fr_Obj val);
fr_Int sys_ObjArray_size_f(fr_Env env, fr_Obj self);
fr_Bool sys_ObjArray_realloc_f(fr_Env env, fr_Obj self, fr_Int newSize);
fr_Obj sys_ObjArray_copyFrom_f(fr_Env env, fr_Obj self, fr_Obj that, fr_Int thatOffset, fr_Int thisOffset, fr_Int length);
void sys_ObjArray_finalize_f(fr_Env env, fr_Obj self);
fr_Obj sys_Slot_find_f(fr_Env env, fr_Obj qname, fr_Bool checked);
fr_Obj sys_Slot_findMethod_f(fr_Env env, fr_Obj qname, fr_Bool checked);
fr_Obj sys_Slot_findField_f(fr_Env env, fr_Obj qname, fr_Bool checked);
fr_Obj sys_Slot_findFunc_f(fr_Env env, fr_Obj qname, fr_Bool checked);
void sys_Slot_make_f(fr_Env env, fr_Obj self);
fr_Obj sys_Slot_parent_f(fr_Env env, fr_Obj self);
fr_Obj sys_Slot_name_f(fr_Env env, fr_Obj self);
fr_Obj sys_Slot_qname_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isField_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isMethod_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isAbstract_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isConst_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isCtor_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isInternal_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isNative_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isOverride_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isPrivate_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isProtected_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isPublic_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isStatic_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isSynthetic_f(fr_Env env, fr_Obj self);
fr_Bool sys_Slot_isVirtual_f(fr_Env env, fr_Obj self);
fr_Obj sys_Slot_facets_f(fr_Env env, fr_Obj self);
fr_Obj sys_Slot_facet_f(fr_Env env, fr_Obj self, fr_Obj type, fr_Bool checked);
fr_Bool sys_Slot_hasFacet_f(fr_Env env, fr_Obj self, fr_Obj type);
fr_Obj sys_Slot_doc_f(fr_Env env, fr_Obj self);
fr_Obj sys_Slot_toStr_f(fr_Env env, fr_Obj self);
fr_Obj sys_Slot_signature_f(fr_Env env, fr_Obj self);
fr_Obj sys_Field_makeSetFunc_f(fr_Env env, fr_Obj vals);
fr_Obj sys_Field_privateMake_f(fr_Env env);
fr_Obj sys_Field_type_f(fr_Env env, fr_Obj self);
fr_Obj sys_Field_get_f(fr_Env env, fr_Obj self, fr_Obj instance);
void sys_Field_set_f(fr_Env env, fr_Obj self, fr_Obj instance, fr_Obj value);
void sys_Field_make_f(fr_Env env, fr_Obj self);
void sys_Func_make_f(fr_Env env, fr_Obj self);
fr_Obj sys_Func_returns_f(fr_Env env, fr_Obj self);
fr_Int sys_Func_arity_f(fr_Env env, fr_Obj self);
fr_Obj sys_Func_params_f(fr_Env env, fr_Obj self);
fr_Obj sys_Func_method_f(fr_Env env, fr_Obj self);
fr_Obj sys_Func_callList_f(fr_Env env, fr_Obj self, fr_Obj args);
fr_Obj sys_Func_callOn_f(fr_Env env, fr_Obj self, fr_Obj target, fr_Obj args);
fr_Obj sys_Func_call_f(fr_Env env, fr_Obj self, fr_Obj a, fr_Obj b, fr_Obj c, fr_Obj d, fr_Obj e, fr_Obj f, fr_Obj g, fr_Obj h);
fr_Obj sys_Func_bind_f(fr_Env env, fr_Obj self, fr_Obj args);
fr_Obj sys_Func_retype_f(fr_Env env, fr_Obj self, fr_Obj t);
void sys_Func_enterCtor_f(fr_Env env, fr_Obj self);
void sys_Func_exitCtor_f(fr_Env env, fr_Obj self);
fr_Obj sys_Method_privateMake_f(fr_Env env);
fr_Obj sys_Method_returns_f(fr_Env env, fr_Obj self);
fr_Obj sys_Method_params_f(fr_Env env, fr_Obj self);
fr_Obj sys_Method_func_f(fr_Env env, fr_Obj self);
fr_Obj sys_Method_callList_f(fr_Env env, fr_Obj self, fr_Obj args);
fr_Obj sys_Method_callOn_f(fr_Env env, fr_Obj self, fr_Obj target, fr_Obj args);
fr_Obj sys_Method_call_f(fr_Env env, fr_Obj self, fr_Obj a, fr_Obj b, fr_Obj c, fr_Obj d, fr_Obj e, fr_Obj f, fr_Obj g, fr_Obj h);
void sys_Method_make_f(fr_Env env, fr_Obj self);
void sys_Param_make_f(fr_Env env, fr_Obj self);
fr_Obj sys_Param_name_f(fr_Env env, fr_Obj self);
fr_Obj sys_Param_type_f(fr_Env env, fr_Obj self);
fr_Bool sys_Param_hasDefault_f(fr_Env env, fr_Obj self);
fr_Obj sys_Param_toStr_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_of_f(fr_Env env, fr_Obj obj);
fr_Obj sys_Pod_list_f(fr_Env env);
fr_Obj sys_Pod_find_f(fr_Env env, fr_Obj name, fr_Bool checked);
fr_Obj sys_Pod_load_f(fr_Env env, fr_Obj in);
void sys_Pod_make_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_name_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_version_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_depends_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_uri_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_toStr_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_meta_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_types_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_type_f(fr_Env env, fr_Obj self, fr_Obj name, fr_Bool checked);
fr_Obj sys_Pod_files_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_file_f(fr_Env env, fr_Obj self, fr_Obj uri, fr_Bool checked);
fr_Obj sys_Pod_doc_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_log_f(fr_Env env, fr_Obj self);
fr_Obj sys_Pod_props_f(fr_Env env, fr_Obj self, fr_Obj uri, fr_Obj maxAge);
fr_Obj sys_Pod_config_f(fr_Env env, fr_Obj self, fr_Obj name, fr_Obj def);
fr_Obj sys_Pod_locale_f(fr_Env env, fr_Obj self, fr_Obj name, fr_Obj def);
void sys_Type_privateMake_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_of_f(fr_Env env, fr_Obj obj);
fr_Obj sys_Type_find_f(fr_Env env, fr_Obj qname, fr_Bool checked);
fr_Obj sys_Type_pod_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_name_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_qname_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_signature_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_base_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_mixins_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_inheritance_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_fits_f(fr_Env env, fr_Obj self, fr_Obj t);
fr_Bool sys_Type_isVal_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isNullable_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_toNullable_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_toNonNullable_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isGeneric_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_params_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_parameterize_f(fr_Env env, fr_Obj self, fr_Obj params);
fr_Obj sys_Type_toListOf_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_emptyList_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isAbstract_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isClass_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isConst_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isEnum_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isFacet_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isFinal_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isInternal_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isMixin_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isPublic_f(fr_Env env, fr_Obj self);
fr_Bool sys_Type_isSynthetic_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_fields_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_methods_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_slots_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_field_f(fr_Env env, fr_Obj self, fr_Obj name, fr_Bool checked);
fr_Obj sys_Type_method_f(fr_Env env, fr_Obj self, fr_Obj name, fr_Bool checked);
fr_Obj sys_Type_slot_f(fr_Env env, fr_Obj self, fr_Obj name, fr_Bool checked);
fr_Obj sys_Type_make_f(fr_Env env, fr_Obj self, fr_Obj args);
fr_Obj sys_Type_facets_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_facet_f(fr_Env env, fr_Obj self, fr_Obj type, fr_Bool checked);
fr_Bool sys_Type_hasFacet_f(fr_Env env, fr_Obj self, fr_Obj type);
fr_Obj sys_Type_doc_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_toStr_f(fr_Env env, fr_Obj self);
fr_Obj sys_Type_toLocale_f(fr_Env env, fr_Obj self);

CF_END
