#include "vm.h"

int sys_Bool__allocSize__();
void sys_Bool_static__init(fr_Env self, void *param, void *ret);
void sys_Bool_fromStr(fr_Env env, void *param, void *ret);
void sys_Bool_privateMake(fr_Env env, void *param, void *ret);
void sys_Bool_equals(fr_Env env, void *param, void *ret);
void sys_Bool_hash(fr_Env env, void *param, void *ret);
void sys_Bool_toStr(fr_Env env, void *param, void *ret);
void sys_Bool_toLocale(fr_Env env, void *param, void *ret);
void sys_Bool_not(fr_Env env, void *param, void *ret);
void sys_Bool_and(fr_Env env, void *param, void *ret);
void sys_Bool_or(fr_Env env, void *param, void *ret);
void sys_Bool_xor(fr_Env env, void *param, void *ret);
void sys_Bool_toCode(fr_Env env, void *param, void *ret);
int sys_Err__allocSize__();
void sys_Err_static__init(fr_Env self, void *param, void *ret);
void sys_Err_make(fr_Env env, void *param, void *ret);
void sys_Err_msg(fr_Env env, void *param, void *ret);
void sys_Err_cause(fr_Env env, void *param, void *ret);
void sys_Err_traceToStr(fr_Env env, void *param, void *ret);
void sys_Err_toStr(fr_Env env, void *param, void *ret);
int sys_Num__allocSize__();
void sys_Num_static__init(fr_Env self, void *param, void *ret);
void sys_Num_make(fr_Env env, void *param, void *ret);
void sys_Num_toInt(fr_Env env, void *param, void *ret);
void sys_Num_toFloat(fr_Env env, void *param, void *ret);
void sys_Num_localeDecimal(fr_Env env, void *param, void *ret);
void sys_Num_localeGrouping(fr_Env env, void *param, void *ret);
void sys_Num_localeMinus(fr_Env env, void *param, void *ret);
void sys_Num_localePercent(fr_Env env, void *param, void *ret);
void sys_Num_localePosInf(fr_Env env, void *param, void *ret);
void sys_Num_localeNegInf(fr_Env env, void *param, void *ret);
void sys_Num_localeNaN(fr_Env env, void *param, void *ret);
int sys_Float__allocSize__();
void sys_Float_static__init(fr_Env self, void *param, void *ret);
void sys_Float_makeBits(fr_Env env, void *param, void *ret);
void sys_Float_makeBits32(fr_Env env, void *param, void *ret);
void sys_Float_fromStr(fr_Env env, void *param, void *ret);
void sys_Float_random(fr_Env env, void *param, void *ret);
void sys_Float_privateMake(fr_Env env, void *param, void *ret);
void sys_Float_equals(fr_Env env, void *param, void *ret);
void sys_Float_approx(fr_Env env, void *param, void *ret);
void sys_Float_compare(fr_Env env, void *param, void *ret);
void sys_Float_isNaN(fr_Env env, void *param, void *ret);
void sys_Float_hash(fr_Env env, void *param, void *ret);
void sys_Float_negate(fr_Env env, void *param, void *ret);
void sys_Float_increment(fr_Env env, void *param, void *ret);
void sys_Float_decrement(fr_Env env, void *param, void *ret);
void sys_Float_mult(fr_Env env, void *param, void *ret);
void sys_Float_multInt(fr_Env env, void *param, void *ret);
void sys_Float_div(fr_Env env, void *param, void *ret);
void sys_Float_divInt(fr_Env env, void *param, void *ret);
void sys_Float_mod(fr_Env env, void *param, void *ret);
void sys_Float_modInt(fr_Env env, void *param, void *ret);
void sys_Float_plus(fr_Env env, void *param, void *ret);
void sys_Float_plusInt(fr_Env env, void *param, void *ret);
void sys_Float_minus(fr_Env env, void *param, void *ret);
void sys_Float_minusInt(fr_Env env, void *param, void *ret);
void sys_Float_abs(fr_Env env, void *param, void *ret);
void sys_Float_min(fr_Env env, void *param, void *ret);
void sys_Float_max(fr_Env env, void *param, void *ret);
void sys_Float_ceil(fr_Env env, void *param, void *ret);
void sys_Float_floor(fr_Env env, void *param, void *ret);
void sys_Float_round(fr_Env env, void *param, void *ret);
void sys_Float_exp(fr_Env env, void *param, void *ret);
void sys_Float_log(fr_Env env, void *param, void *ret);
void sys_Float_log10(fr_Env env, void *param, void *ret);
void sys_Float_pow(fr_Env env, void *param, void *ret);
void sys_Float_sqrt(fr_Env env, void *param, void *ret);
void sys_Float_acos(fr_Env env, void *param, void *ret);
void sys_Float_asin(fr_Env env, void *param, void *ret);
void sys_Float_atan(fr_Env env, void *param, void *ret);
void sys_Float_atan2(fr_Env env, void *param, void *ret);
void sys_Float_cos(fr_Env env, void *param, void *ret);
void sys_Float_cosh(fr_Env env, void *param, void *ret);
void sys_Float_sin(fr_Env env, void *param, void *ret);
void sys_Float_sinh(fr_Env env, void *param, void *ret);
void sys_Float_tan(fr_Env env, void *param, void *ret);
void sys_Float_tanh(fr_Env env, void *param, void *ret);
void sys_Float_toDegrees(fr_Env env, void *param, void *ret);
void sys_Float_toRadians(fr_Env env, void *param, void *ret);
void sys_Float_bits(fr_Env env, void *param, void *ret);
void sys_Float_bits32(fr_Env env, void *param, void *ret);
void sys_Float_toStr(fr_Env env, void *param, void *ret);
void sys_Float_toCode(fr_Env env, void *param, void *ret);
void sys_Float_make(fr_Env env, void *param, void *ret);
int sys_Int__allocSize__();
void sys_Int_static__init(fr_Env self, void *param, void *ret);
void sys_Int_fromStr(fr_Env env, void *param, void *ret);
void sys_Int_random(fr_Env env, void *param, void *ret);
void sys_Int_privateMake(fr_Env env, void *param, void *ret);
void sys_Int_equals(fr_Env env, void *param, void *ret);
void sys_Int_compare(fr_Env env, void *param, void *ret);
void sys_Int_hash(fr_Env env, void *param, void *ret);
void sys_Int_negate(fr_Env env, void *param, void *ret);
void sys_Int_increment(fr_Env env, void *param, void *ret);
void sys_Int_decrement(fr_Env env, void *param, void *ret);
void sys_Int_mult(fr_Env env, void *param, void *ret);
void sys_Int_multFloat(fr_Env env, void *param, void *ret);
void sys_Int_div(fr_Env env, void *param, void *ret);
void sys_Int_divFloat(fr_Env env, void *param, void *ret);
void sys_Int_mod(fr_Env env, void *param, void *ret);
void sys_Int_modFloat(fr_Env env, void *param, void *ret);
void sys_Int_plus(fr_Env env, void *param, void *ret);
void sys_Int_plusFloat(fr_Env env, void *param, void *ret);
void sys_Int_minus(fr_Env env, void *param, void *ret);
void sys_Int_minusFloat(fr_Env env, void *param, void *ret);
void sys_Int_not(fr_Env env, void *param, void *ret);
void sys_Int_and(fr_Env env, void *param, void *ret);
void sys_Int_or(fr_Env env, void *param, void *ret);
void sys_Int_xor(fr_Env env, void *param, void *ret);
void sys_Int_shiftl(fr_Env env, void *param, void *ret);
void sys_Int_shiftr(fr_Env env, void *param, void *ret);
void sys_Int_abs(fr_Env env, void *param, void *ret);
void sys_Int_min(fr_Env env, void *param, void *ret);
void sys_Int_max(fr_Env env, void *param, void *ret);
void sys_Int_pow(fr_Env env, void *param, void *ret);
void sys_Int_isEven(fr_Env env, void *param, void *ret);
void sys_Int_isOdd(fr_Env env, void *param, void *ret);
void sys_Int_isSpace(fr_Env env, void *param, void *ret);
void sys_Int_isAlpha(fr_Env env, void *param, void *ret);
void sys_Int_isAlphaNum(fr_Env env, void *param, void *ret);
void sys_Int_isUpper(fr_Env env, void *param, void *ret);
void sys_Int_isLower(fr_Env env, void *param, void *ret);
void sys_Int_upper(fr_Env env, void *param, void *ret);
void sys_Int_lower(fr_Env env, void *param, void *ret);
void sys_Int_isDigit(fr_Env env, void *param, void *ret);
void sys_Int_toDigit(fr_Env env, void *param, void *ret);
void sys_Int_fromDigit(fr_Env env, void *param, void *ret);
void sys_Int_equalsIgnoreCase(fr_Env env, void *param, void *ret);
void sys_Int_localeIsUpper(fr_Env env, void *param, void *ret);
void sys_Int_localeIsLower(fr_Env env, void *param, void *ret);
void sys_Int_localeUpper(fr_Env env, void *param, void *ret);
void sys_Int_localeLower(fr_Env env, void *param, void *ret);
void sys_Int_toStr(fr_Env env, void *param, void *ret);
void sys_Int_toHex(fr_Env env, void *param, void *ret);
void sys_Int_toRadix(fr_Env env, void *param, void *ret);
void sys_Int_toChar(fr_Env env, void *param, void *ret);
void sys_Int_toCode(fr_Env env, void *param, void *ret);
void sys_Int_times(fr_Env env, void *param, void *ret);
void sys_Int_make(fr_Env env, void *param, void *ret);
int sys_Obj__allocSize__();
void sys_Obj_static__init(fr_Env self, void *param, void *ret);
void sys_Obj_make(fr_Env env, void *param, void *ret);
void sys_Obj_equals(fr_Env env, void *param, void *ret);
void sys_Obj_compare(fr_Env env, void *param, void *ret);
void sys_Obj_hash(fr_Env env, void *param, void *ret);
void sys_Obj_toStr(fr_Env env, void *param, void *ret);
void sys_Obj_trap(fr_Env env, void *param, void *ret);
void sys_Obj_with(fr_Env env, void *param, void *ret);
void sys_Obj_isImmutable(fr_Env env, void *param, void *ret);
void sys_Obj_toImmutable(fr_Env env, void *param, void *ret);
void sys_Obj_typeof(fr_Env env, void *param, void *ret);
void sys_Obj_finalize(fr_Env env, void *param, void *ret);
void sys_Obj_echo(fr_Env env, void *param, void *ret);
int sys_Str__allocSize__();
void sys_Str_static__init(fr_Env self, void *param, void *ret);
void sys_Str_privateMake(fr_Env env, void *param, void *ret);
void sys_Str_fromChars(fr_Env env, void *param, void *ret);
void sys_Str_equals(fr_Env env, void *param, void *ret);
void sys_Str_equalsIgnoreCase(fr_Env env, void *param, void *ret);
void sys_Str_compare(fr_Env env, void *param, void *ret);
void sys_Str_compareIgnoreCase(fr_Env env, void *param, void *ret);
void sys_Str_hash(fr_Env env, void *param, void *ret);
void sys_Str_toStr(fr_Env env, void *param, void *ret);
void sys_Str_toLocale(fr_Env env, void *param, void *ret);
void sys_Str_isEmpty(fr_Env env, void *param, void *ret);
void sys_Str_size(fr_Env env, void *param, void *ret);
void sys_Str_intern(fr_Env env, void *param, void *ret);
void sys_Str_startsWith(fr_Env env, void *param, void *ret);
void sys_Str_endsWith(fr_Env env, void *param, void *ret);
void sys_Str_index(fr_Env env, void *param, void *ret);
void sys_Str_indexr(fr_Env env, void *param, void *ret);
void sys_Str_indexIgnoreCase(fr_Env env, void *param, void *ret);
void sys_Str_indexrIgnoreCase(fr_Env env, void *param, void *ret);
void sys_Str_contains(fr_Env env, void *param, void *ret);
void sys_Str_containsChar(fr_Env env, void *param, void *ret);
void sys_Str_get(fr_Env env, void *param, void *ret);
void sys_Str_getSafe(fr_Env env, void *param, void *ret);
void sys_Str_getRange(fr_Env env, void *param, void *ret);
void sys_Str_plus(fr_Env env, void *param, void *ret);
void sys_Str_chars(fr_Env env, void *param, void *ret);
void sys_Str_each(fr_Env env, void *param, void *ret);
void sys_Str_eachr(fr_Env env, void *param, void *ret);
void sys_Str_any(fr_Env env, void *param, void *ret);
void sys_Str_all(fr_Env env, void *param, void *ret);
void sys_Str_spaces(fr_Env env, void *param, void *ret);
void sys_Str_lower(fr_Env env, void *param, void *ret);
void sys_Str_upper(fr_Env env, void *param, void *ret);
void sys_Str_capitalize(fr_Env env, void *param, void *ret);
void sys_Str_decapitalize(fr_Env env, void *param, void *ret);
void sys_Str_toDisplayName(fr_Env env, void *param, void *ret);
void sys_Str_fromDisplayName(fr_Env env, void *param, void *ret);
void sys_Str_justl(fr_Env env, void *param, void *ret);
void sys_Str_justr(fr_Env env, void *param, void *ret);
void sys_Str_padl(fr_Env env, void *param, void *ret);
void sys_Str_padr(fr_Env env, void *param, void *ret);
void sys_Str_reverse(fr_Env env, void *param, void *ret);
void sys_Str_trim(fr_Env env, void *param, void *ret);
void sys_Str_trimToNull(fr_Env env, void *param, void *ret);
void sys_Str_trimStart(fr_Env env, void *param, void *ret);
void sys_Str_trimEnd(fr_Env env, void *param, void *ret);
void sys_Str_split(fr_Env env, void *param, void *ret);
void sys_Str_splitLines(fr_Env env, void *param, void *ret);
void sys_Str_replace(fr_Env env, void *param, void *ret);
void sys_Str_numNewlines(fr_Env env, void *param, void *ret);
void sys_Str_isAscii(fr_Env env, void *param, void *ret);
void sys_Str_isSpace(fr_Env env, void *param, void *ret);
void sys_Str_isUpper(fr_Env env, void *param, void *ret);
void sys_Str_isLower(fr_Env env, void *param, void *ret);
void sys_Str_isAlpha(fr_Env env, void *param, void *ret);
void sys_Str_isAlphaNum(fr_Env env, void *param, void *ret);
void sys_Str_localeCompare(fr_Env env, void *param, void *ret);
void sys_Str_localeLower(fr_Env env, void *param, void *ret);
void sys_Str_localeUpper(fr_Env env, void *param, void *ret);
void sys_Str_localeCapitalize(fr_Env env, void *param, void *ret);
void sys_Str_localeDecapitalize(fr_Env env, void *param, void *ret);
void sys_Str_toBool(fr_Env env, void *param, void *ret);
void sys_Str_toInt(fr_Env env, void *param, void *ret);
void sys_Str_toFloat(fr_Env env, void *param, void *ret);
void sys_Str_toCode(fr_Env env, void *param, void *ret);
void sys_Str_toXml(fr_Env env, void *param, void *ret);
void sys_Str_finalize(fr_Env env, void *param, void *ret);
void sys_Str_static__init(fr_Env env, void *param, void *ret);
int sys_StrBuf__allocSize__();
void sys_StrBuf_static__init(fr_Env self, void *param, void *ret);
void sys_StrBuf_make(fr_Env env, void *param, void *ret);
void sys_StrBuf_isEmpty(fr_Env env, void *param, void *ret);
void sys_StrBuf_size(fr_Env env, void *param, void *ret);
void sys_StrBuf_capacity(fr_Env env, void *param, void *ret);
void sys_StrBuf_capacity_(fr_Env env, void *param, void *ret);
void sys_StrBuf_get(fr_Env env, void *param, void *ret);
void sys_StrBuf_getRange(fr_Env env, void *param, void *ret);
void sys_StrBuf_set(fr_Env env, void *param, void *ret);
void sys_StrBuf_add(fr_Env env, void *param, void *ret);
void sys_StrBuf_addChar(fr_Env env, void *param, void *ret);
void sys_StrBuf_join(fr_Env env, void *param, void *ret);
void sys_StrBuf_insert(fr_Env env, void *param, void *ret);
void sys_StrBuf_remove(fr_Env env, void *param, void *ret);
void sys_StrBuf_removeRange(fr_Env env, void *param, void *ret);
void sys_StrBuf_replaceRange(fr_Env env, void *param, void *ret);
void sys_StrBuf_clear(fr_Env env, void *param, void *ret);
void sys_StrBuf_toStr(fr_Env env, void *param, void *ret);
void sys_StrBuf_finalize(fr_Env env, void *param, void *ret);
int sys_This__allocSize__();
void sys_This_static__init(fr_Env self, void *param, void *ret);
void sys_This_make(fr_Env env, void *param, void *ret);
int sys_Void__allocSize__();
void sys_Void_static__init(fr_Env self, void *param, void *ret);
void sys_Void_make(fr_Env env, void *param, void *ret);
int sys_ByteArray__allocSize__();
void sys_ByteArray_static__init(fr_Env self, void *param, void *ret);
void sys_ByteArray_make(fr_Env env, void *param, void *ret);
void sys_ByteArray_get(fr_Env env, void *param, void *ret);
void sys_ByteArray_set(fr_Env env, void *param, void *ret);
void sys_ByteArray_size(fr_Env env, void *param, void *ret);
void sys_ByteArray_realloc(fr_Env env, void *param, void *ret);
void sys_ByteArray_copyFrom(fr_Env env, void *param, void *ret);
void sys_ByteArray_finalize(fr_Env env, void *param, void *ret);
int sys_IntArray__allocSize__();
void sys_IntArray_static__init(fr_Env self, void *param, void *ret);
void sys_IntArray_make(fr_Env env, void *param, void *ret);
void sys_IntArray_get(fr_Env env, void *param, void *ret);
void sys_IntArray_set(fr_Env env, void *param, void *ret);
void sys_IntArray_size(fr_Env env, void *param, void *ret);
void sys_IntArray_realloc(fr_Env env, void *param, void *ret);
void sys_IntArray_copyFrom(fr_Env env, void *param, void *ret);
void sys_IntArray_finalize(fr_Env env, void *param, void *ret);
int sys_ObjArray__allocSize__();
void sys_ObjArray_static__init(fr_Env self, void *param, void *ret);
void sys_ObjArray_make(fr_Env env, void *param, void *ret);
void sys_ObjArray_get(fr_Env env, void *param, void *ret);
void sys_ObjArray_set(fr_Env env, void *param, void *ret);
void sys_ObjArray_size(fr_Env env, void *param, void *ret);
void sys_ObjArray_realloc(fr_Env env, void *param, void *ret);
void sys_ObjArray_copyFrom(fr_Env env, void *param, void *ret);
void sys_ObjArray_finalize(fr_Env env, void *param, void *ret);
int sys_Slot__allocSize__();
void sys_Slot_static__init(fr_Env self, void *param, void *ret);
void sys_Slot_find(fr_Env env, void *param, void *ret);
void sys_Slot_findMethod(fr_Env env, void *param, void *ret);
void sys_Slot_findField(fr_Env env, void *param, void *ret);
void sys_Slot_findFunc(fr_Env env, void *param, void *ret);
void sys_Slot_make(fr_Env env, void *param, void *ret);
void sys_Slot_parent(fr_Env env, void *param, void *ret);
void sys_Slot_name(fr_Env env, void *param, void *ret);
void sys_Slot_qname(fr_Env env, void *param, void *ret);
void sys_Slot_isField(fr_Env env, void *param, void *ret);
void sys_Slot_isMethod(fr_Env env, void *param, void *ret);
void sys_Slot_isAbstract(fr_Env env, void *param, void *ret);
void sys_Slot_isConst(fr_Env env, void *param, void *ret);
void sys_Slot_isCtor(fr_Env env, void *param, void *ret);
void sys_Slot_isInternal(fr_Env env, void *param, void *ret);
void sys_Slot_isNative(fr_Env env, void *param, void *ret);
void sys_Slot_isOverride(fr_Env env, void *param, void *ret);
void sys_Slot_isPrivate(fr_Env env, void *param, void *ret);
void sys_Slot_isProtected(fr_Env env, void *param, void *ret);
void sys_Slot_isPublic(fr_Env env, void *param, void *ret);
void sys_Slot_isStatic(fr_Env env, void *param, void *ret);
void sys_Slot_isSynthetic(fr_Env env, void *param, void *ret);
void sys_Slot_isVirtual(fr_Env env, void *param, void *ret);
void sys_Slot_facets(fr_Env env, void *param, void *ret);
void sys_Slot_facet(fr_Env env, void *param, void *ret);
void sys_Slot_hasFacet(fr_Env env, void *param, void *ret);
void sys_Slot_doc(fr_Env env, void *param, void *ret);
void sys_Slot_toStr(fr_Env env, void *param, void *ret);
void sys_Slot_signature(fr_Env env, void *param, void *ret);
int sys_Field__allocSize__();
void sys_Field_static__init(fr_Env self, void *param, void *ret);
void sys_Field_makeSetFunc(fr_Env env, void *param, void *ret);
void sys_Field_privateMake(fr_Env env, void *param, void *ret);
void sys_Field_type(fr_Env env, void *param, void *ret);
void sys_Field_get(fr_Env env, void *param, void *ret);
void sys_Field_set(fr_Env env, void *param, void *ret);
void sys_Field_make(fr_Env env, void *param, void *ret);
int sys_Func__allocSize__();
void sys_Func_static__init(fr_Env self, void *param, void *ret);
void sys_Func_make(fr_Env env, void *param, void *ret);
void sys_Func_returns(fr_Env env, void *param, void *ret);
void sys_Func_arity(fr_Env env, void *param, void *ret);
void sys_Func_params(fr_Env env, void *param, void *ret);
void sys_Func_method(fr_Env env, void *param, void *ret);
void sys_Func_callList(fr_Env env, void *param, void *ret);
void sys_Func_callOn(fr_Env env, void *param, void *ret);
void sys_Func_call(fr_Env env, void *param, void *ret);
void sys_Func_bind(fr_Env env, void *param, void *ret);
void sys_Func_retype(fr_Env env, void *param, void *ret);
void sys_Func_enterCtor(fr_Env env, void *param, void *ret);
void sys_Func_exitCtor(fr_Env env, void *param, void *ret);
int sys_Method__allocSize__();
void sys_Method_static__init(fr_Env self, void *param, void *ret);
void sys_Method_privateMake(fr_Env env, void *param, void *ret);
void sys_Method_returns(fr_Env env, void *param, void *ret);
void sys_Method_params(fr_Env env, void *param, void *ret);
void sys_Method_func(fr_Env env, void *param, void *ret);
void sys_Method_callList(fr_Env env, void *param, void *ret);
void sys_Method_callOn(fr_Env env, void *param, void *ret);
void sys_Method_call(fr_Env env, void *param, void *ret);
void sys_Method_make(fr_Env env, void *param, void *ret);
int sys_Param__allocSize__();
void sys_Param_static__init(fr_Env self, void *param, void *ret);
void sys_Param_make(fr_Env env, void *param, void *ret);
void sys_Param_name(fr_Env env, void *param, void *ret);
void sys_Param_type(fr_Env env, void *param, void *ret);
void sys_Param_hasDefault(fr_Env env, void *param, void *ret);
void sys_Param_toStr(fr_Env env, void *param, void *ret);
int sys_Pod__allocSize__();
void sys_Pod_static__init(fr_Env self, void *param, void *ret);
void sys_Pod_of(fr_Env env, void *param, void *ret);
void sys_Pod_list(fr_Env env, void *param, void *ret);
void sys_Pod_find(fr_Env env, void *param, void *ret);
void sys_Pod_load(fr_Env env, void *param, void *ret);
void sys_Pod_make(fr_Env env, void *param, void *ret);
void sys_Pod_name(fr_Env env, void *param, void *ret);
void sys_Pod_version(fr_Env env, void *param, void *ret);
void sys_Pod_depends(fr_Env env, void *param, void *ret);
void sys_Pod_uri(fr_Env env, void *param, void *ret);
void sys_Pod_toStr(fr_Env env, void *param, void *ret);
void sys_Pod_meta(fr_Env env, void *param, void *ret);
void sys_Pod_types(fr_Env env, void *param, void *ret);
void sys_Pod_type(fr_Env env, void *param, void *ret);
void sys_Pod_files(fr_Env env, void *param, void *ret);
void sys_Pod_file(fr_Env env, void *param, void *ret);
void sys_Pod_doc(fr_Env env, void *param, void *ret);
void sys_Pod_log(fr_Env env, void *param, void *ret);
void sys_Pod_props(fr_Env env, void *param, void *ret);
void sys_Pod_config(fr_Env env, void *param, void *ret);
void sys_Pod_locale(fr_Env env, void *param, void *ret);
int sys_Type__allocSize__();
void sys_Type_static__init(fr_Env self, void *param, void *ret);
void sys_Type_privateMake(fr_Env env, void *param, void *ret);
void sys_Type_of(fr_Env env, void *param, void *ret);
void sys_Type_find(fr_Env env, void *param, void *ret);
void sys_Type_pod(fr_Env env, void *param, void *ret);
void sys_Type_name(fr_Env env, void *param, void *ret);
void sys_Type_qname(fr_Env env, void *param, void *ret);
void sys_Type_signature(fr_Env env, void *param, void *ret);
void sys_Type_base(fr_Env env, void *param, void *ret);
void sys_Type_mixins(fr_Env env, void *param, void *ret);
void sys_Type_inheritance(fr_Env env, void *param, void *ret);
void sys_Type_fits(fr_Env env, void *param, void *ret);
void sys_Type_isVal(fr_Env env, void *param, void *ret);
void sys_Type_isNullable(fr_Env env, void *param, void *ret);
void sys_Type_toNullable(fr_Env env, void *param, void *ret);
void sys_Type_toNonNullable(fr_Env env, void *param, void *ret);
void sys_Type_isGeneric(fr_Env env, void *param, void *ret);
void sys_Type_params(fr_Env env, void *param, void *ret);
void sys_Type_parameterize(fr_Env env, void *param, void *ret);
void sys_Type_toListOf(fr_Env env, void *param, void *ret);
void sys_Type_emptyList(fr_Env env, void *param, void *ret);
void sys_Type_isAbstract(fr_Env env, void *param, void *ret);
void sys_Type_isClass(fr_Env env, void *param, void *ret);
void sys_Type_isConst(fr_Env env, void *param, void *ret);
void sys_Type_isEnum(fr_Env env, void *param, void *ret);
void sys_Type_isFacet(fr_Env env, void *param, void *ret);
void sys_Type_isFinal(fr_Env env, void *param, void *ret);
void sys_Type_isInternal(fr_Env env, void *param, void *ret);
void sys_Type_isMixin(fr_Env env, void *param, void *ret);
void sys_Type_isPublic(fr_Env env, void *param, void *ret);
void sys_Type_isSynthetic(fr_Env env, void *param, void *ret);
void sys_Type_fields(fr_Env env, void *param, void *ret);
void sys_Type_methods(fr_Env env, void *param, void *ret);
void sys_Type_slots(fr_Env env, void *param, void *ret);
void sys_Type_field(fr_Env env, void *param, void *ret);
void sys_Type_method(fr_Env env, void *param, void *ret);
void sys_Type_slot(fr_Env env, void *param, void *ret);
void sys_Type_make(fr_Env env, void *param, void *ret);
void sys_Type_facets(fr_Env env, void *param, void *ret);
void sys_Type_facet(fr_Env env, void *param, void *ret);
void sys_Type_hasFacet(fr_Env env, void *param, void *ret);
void sys_Type_doc(fr_Env env, void *param, void *ret);
void sys_Type_toStr(fr_Env env, void *param, void *ret);
void sys_Type_toLocale(fr_Env env, void *param, void *ret);

void sys_register(fr_Fvm vm) {
    fr_registerMethod(vm, "sys_Bool__allocSize__", (fr_NativeFunc)sys_Bool__allocSize__);
    fr_registerMethod(vm, "sys_Bool_static$init", (fr_NativeFunc)sys_Bool_static__init);
    fr_registerMethod(vm, "sys_Bool_fromStr", sys_Bool_fromStr);
    fr_registerMethod(vm, "sys_Bool_privateMake", sys_Bool_privateMake);
    fr_registerMethod(vm, "sys_Bool_equals", sys_Bool_equals);
    fr_registerMethod(vm, "sys_Bool_hash", sys_Bool_hash);
    fr_registerMethod(vm, "sys_Bool_toStr", sys_Bool_toStr);
    fr_registerMethod(vm, "sys_Bool_toLocale", sys_Bool_toLocale);
    fr_registerMethod(vm, "sys_Bool_not", sys_Bool_not);
    fr_registerMethod(vm, "sys_Bool_and", sys_Bool_and);
    fr_registerMethod(vm, "sys_Bool_or", sys_Bool_or);
    fr_registerMethod(vm, "sys_Bool_xor", sys_Bool_xor);
    fr_registerMethod(vm, "sys_Bool_toCode", sys_Bool_toCode);
    fr_registerMethod(vm, "sys_Err__allocSize__", (fr_NativeFunc)sys_Err__allocSize__);
    fr_registerMethod(vm, "sys_Err_static$init", (fr_NativeFunc)sys_Err_static__init);
    fr_registerMethod(vm, "sys_Err_make", sys_Err_make);
    fr_registerMethod(vm, "sys_Err_msg", sys_Err_msg);
    fr_registerMethod(vm, "sys_Err_cause", sys_Err_cause);
    fr_registerMethod(vm, "sys_Err_traceToStr", sys_Err_traceToStr);
    fr_registerMethod(vm, "sys_Err_toStr", sys_Err_toStr);
    fr_registerMethod(vm, "sys_Num__allocSize__", (fr_NativeFunc)sys_Num__allocSize__);
    fr_registerMethod(vm, "sys_Num_static$init", (fr_NativeFunc)sys_Num_static__init);
    fr_registerMethod(vm, "sys_Num_make", sys_Num_make);
    fr_registerMethod(vm, "sys_Num_toInt", sys_Num_toInt);
    fr_registerMethod(vm, "sys_Num_toFloat", sys_Num_toFloat);
    fr_registerMethod(vm, "sys_Num_localeDecimal", sys_Num_localeDecimal);
    fr_registerMethod(vm, "sys_Num_localeGrouping", sys_Num_localeGrouping);
    fr_registerMethod(vm, "sys_Num_localeMinus", sys_Num_localeMinus);
    fr_registerMethod(vm, "sys_Num_localePercent", sys_Num_localePercent);
    fr_registerMethod(vm, "sys_Num_localePosInf", sys_Num_localePosInf);
    fr_registerMethod(vm, "sys_Num_localeNegInf", sys_Num_localeNegInf);
    fr_registerMethod(vm, "sys_Num_localeNaN", sys_Num_localeNaN);
    fr_registerMethod(vm, "sys_Float__allocSize__", (fr_NativeFunc)sys_Float__allocSize__);
    fr_registerMethod(vm, "sys_Float_static$init", (fr_NativeFunc)sys_Float_static__init);
    fr_registerMethod(vm, "sys_Float_makeBits", sys_Float_makeBits);
    fr_registerMethod(vm, "sys_Float_makeBits32", sys_Float_makeBits32);
    fr_registerMethod(vm, "sys_Float_fromStr", sys_Float_fromStr);
    fr_registerMethod(vm, "sys_Float_random", sys_Float_random);
    fr_registerMethod(vm, "sys_Float_privateMake", sys_Float_privateMake);
    fr_registerMethod(vm, "sys_Float_equals", sys_Float_equals);
    fr_registerMethod(vm, "sys_Float_approx", sys_Float_approx);
    fr_registerMethod(vm, "sys_Float_compare", sys_Float_compare);
    fr_registerMethod(vm, "sys_Float_isNaN", sys_Float_isNaN);
    fr_registerMethod(vm, "sys_Float_hash", sys_Float_hash);
    fr_registerMethod(vm, "sys_Float_negate", sys_Float_negate);
    fr_registerMethod(vm, "sys_Float_increment", sys_Float_increment);
    fr_registerMethod(vm, "sys_Float_decrement", sys_Float_decrement);
    fr_registerMethod(vm, "sys_Float_mult", sys_Float_mult);
    fr_registerMethod(vm, "sys_Float_multInt", sys_Float_multInt);
    fr_registerMethod(vm, "sys_Float_div", sys_Float_div);
    fr_registerMethod(vm, "sys_Float_divInt", sys_Float_divInt);
    fr_registerMethod(vm, "sys_Float_mod", sys_Float_mod);
    fr_registerMethod(vm, "sys_Float_modInt", sys_Float_modInt);
    fr_registerMethod(vm, "sys_Float_plus", sys_Float_plus);
    fr_registerMethod(vm, "sys_Float_plusInt", sys_Float_plusInt);
    fr_registerMethod(vm, "sys_Float_minus", sys_Float_minus);
    fr_registerMethod(vm, "sys_Float_minusInt", sys_Float_minusInt);
    fr_registerMethod(vm, "sys_Float_abs", sys_Float_abs);
    fr_registerMethod(vm, "sys_Float_min", sys_Float_min);
    fr_registerMethod(vm, "sys_Float_max", sys_Float_max);
    fr_registerMethod(vm, "sys_Float_ceil", sys_Float_ceil);
    fr_registerMethod(vm, "sys_Float_floor", sys_Float_floor);
    fr_registerMethod(vm, "sys_Float_round", sys_Float_round);
    fr_registerMethod(vm, "sys_Float_exp", sys_Float_exp);
    fr_registerMethod(vm, "sys_Float_log", sys_Float_log);
    fr_registerMethod(vm, "sys_Float_log10", sys_Float_log10);
    fr_registerMethod(vm, "sys_Float_pow", sys_Float_pow);
    fr_registerMethod(vm, "sys_Float_sqrt", sys_Float_sqrt);
    fr_registerMethod(vm, "sys_Float_acos", sys_Float_acos);
    fr_registerMethod(vm, "sys_Float_asin", sys_Float_asin);
    fr_registerMethod(vm, "sys_Float_atan", sys_Float_atan);
    fr_registerMethod(vm, "sys_Float_atan2", sys_Float_atan2);
    fr_registerMethod(vm, "sys_Float_cos", sys_Float_cos);
    fr_registerMethod(vm, "sys_Float_cosh", sys_Float_cosh);
    fr_registerMethod(vm, "sys_Float_sin", sys_Float_sin);
    fr_registerMethod(vm, "sys_Float_sinh", sys_Float_sinh);
    fr_registerMethod(vm, "sys_Float_tan", sys_Float_tan);
    fr_registerMethod(vm, "sys_Float_tanh", sys_Float_tanh);
    fr_registerMethod(vm, "sys_Float_toDegrees", sys_Float_toDegrees);
    fr_registerMethod(vm, "sys_Float_toRadians", sys_Float_toRadians);
    fr_registerMethod(vm, "sys_Float_bits", sys_Float_bits);
    fr_registerMethod(vm, "sys_Float_bits32", sys_Float_bits32);
    fr_registerMethod(vm, "sys_Float_toStr", sys_Float_toStr);
    fr_registerMethod(vm, "sys_Float_toCode", sys_Float_toCode);
    fr_registerMethod(vm, "sys_Float_make", sys_Float_make);
    fr_registerMethod(vm, "sys_Int__allocSize__", (fr_NativeFunc)sys_Int__allocSize__);
    fr_registerMethod(vm, "sys_Int_static$init", (fr_NativeFunc)sys_Int_static__init);
    fr_registerMethod(vm, "sys_Int_fromStr", sys_Int_fromStr);
    fr_registerMethod(vm, "sys_Int_random", sys_Int_random);
    fr_registerMethod(vm, "sys_Int_privateMake", sys_Int_privateMake);
    fr_registerMethod(vm, "sys_Int_equals", sys_Int_equals);
    fr_registerMethod(vm, "sys_Int_compare", sys_Int_compare);
    fr_registerMethod(vm, "sys_Int_hash", sys_Int_hash);
    fr_registerMethod(vm, "sys_Int_negate", sys_Int_negate);
    fr_registerMethod(vm, "sys_Int_increment", sys_Int_increment);
    fr_registerMethod(vm, "sys_Int_decrement", sys_Int_decrement);
    fr_registerMethod(vm, "sys_Int_mult", sys_Int_mult);
    fr_registerMethod(vm, "sys_Int_multFloat", sys_Int_multFloat);
    fr_registerMethod(vm, "sys_Int_div", sys_Int_div);
    fr_registerMethod(vm, "sys_Int_divFloat", sys_Int_divFloat);
    fr_registerMethod(vm, "sys_Int_mod", sys_Int_mod);
    fr_registerMethod(vm, "sys_Int_modFloat", sys_Int_modFloat);
    fr_registerMethod(vm, "sys_Int_plus", sys_Int_plus);
    fr_registerMethod(vm, "sys_Int_plusFloat", sys_Int_plusFloat);
    fr_registerMethod(vm, "sys_Int_minus", sys_Int_minus);
    fr_registerMethod(vm, "sys_Int_minusFloat", sys_Int_minusFloat);
    fr_registerMethod(vm, "sys_Int_not", sys_Int_not);
    fr_registerMethod(vm, "sys_Int_and", sys_Int_and);
    fr_registerMethod(vm, "sys_Int_or", sys_Int_or);
    fr_registerMethod(vm, "sys_Int_xor", sys_Int_xor);
    fr_registerMethod(vm, "sys_Int_shiftl", sys_Int_shiftl);
    fr_registerMethod(vm, "sys_Int_shiftr", sys_Int_shiftr);
    fr_registerMethod(vm, "sys_Int_abs", sys_Int_abs);
    fr_registerMethod(vm, "sys_Int_min", sys_Int_min);
    fr_registerMethod(vm, "sys_Int_max", sys_Int_max);
    fr_registerMethod(vm, "sys_Int_pow", sys_Int_pow);
    fr_registerMethod(vm, "sys_Int_isEven", sys_Int_isEven);
    fr_registerMethod(vm, "sys_Int_isOdd", sys_Int_isOdd);
    fr_registerMethod(vm, "sys_Int_isSpace", sys_Int_isSpace);
    fr_registerMethod(vm, "sys_Int_isAlpha", sys_Int_isAlpha);
    fr_registerMethod(vm, "sys_Int_isAlphaNum", sys_Int_isAlphaNum);
    fr_registerMethod(vm, "sys_Int_isUpper", sys_Int_isUpper);
    fr_registerMethod(vm, "sys_Int_isLower", sys_Int_isLower);
    fr_registerMethod(vm, "sys_Int_upper", sys_Int_upper);
    fr_registerMethod(vm, "sys_Int_lower", sys_Int_lower);
    fr_registerMethod(vm, "sys_Int_isDigit", sys_Int_isDigit);
    fr_registerMethod(vm, "sys_Int_toDigit", sys_Int_toDigit);
    fr_registerMethod(vm, "sys_Int_fromDigit", sys_Int_fromDigit);
    fr_registerMethod(vm, "sys_Int_equalsIgnoreCase", sys_Int_equalsIgnoreCase);
    fr_registerMethod(vm, "sys_Int_localeIsUpper", sys_Int_localeIsUpper);
    fr_registerMethod(vm, "sys_Int_localeIsLower", sys_Int_localeIsLower);
    fr_registerMethod(vm, "sys_Int_localeUpper", sys_Int_localeUpper);
    fr_registerMethod(vm, "sys_Int_localeLower", sys_Int_localeLower);
    fr_registerMethod(vm, "sys_Int_toStr", sys_Int_toStr);
    fr_registerMethod(vm, "sys_Int_toHex", sys_Int_toHex);
    fr_registerMethod(vm, "sys_Int_toRadix", sys_Int_toRadix);
    fr_registerMethod(vm, "sys_Int_toChar", sys_Int_toChar);
    fr_registerMethod(vm, "sys_Int_toCode", sys_Int_toCode);
    fr_registerMethod(vm, "sys_Int_times", sys_Int_times);
    fr_registerMethod(vm, "sys_Int_make", sys_Int_make);
    fr_registerMethod(vm, "sys_Obj__allocSize__", (fr_NativeFunc)sys_Obj__allocSize__);
    fr_registerMethod(vm, "sys_Obj_static$init", (fr_NativeFunc)sys_Obj_static__init);
    fr_registerMethod(vm, "sys_Obj_make", sys_Obj_make);
    fr_registerMethod(vm, "sys_Obj_equals", sys_Obj_equals);
    fr_registerMethod(vm, "sys_Obj_compare", sys_Obj_compare);
    fr_registerMethod(vm, "sys_Obj_hash", sys_Obj_hash);
    fr_registerMethod(vm, "sys_Obj_toStr", sys_Obj_toStr);
    fr_registerMethod(vm, "sys_Obj_trap", sys_Obj_trap);
    fr_registerMethod(vm, "sys_Obj_with", sys_Obj_with);
    fr_registerMethod(vm, "sys_Obj_isImmutable", sys_Obj_isImmutable);
    fr_registerMethod(vm, "sys_Obj_toImmutable", sys_Obj_toImmutable);
    fr_registerMethod(vm, "sys_Obj_typeof", sys_Obj_typeof);
    fr_registerMethod(vm, "sys_Obj_finalize", sys_Obj_finalize);
    fr_registerMethod(vm, "sys_Obj_echo", sys_Obj_echo);
    fr_registerMethod(vm, "sys_Str__allocSize__", (fr_NativeFunc)sys_Str__allocSize__);
    fr_registerMethod(vm, "sys_Str_static$init", (fr_NativeFunc)sys_Str_static__init);
    fr_registerMethod(vm, "sys_Str_privateMake", sys_Str_privateMake);
    fr_registerMethod(vm, "sys_Str_fromChars", sys_Str_fromChars);
    fr_registerMethod(vm, "sys_Str_equals", sys_Str_equals);
    fr_registerMethod(vm, "sys_Str_equalsIgnoreCase", sys_Str_equalsIgnoreCase);
    fr_registerMethod(vm, "sys_Str_compare", sys_Str_compare);
    fr_registerMethod(vm, "sys_Str_compareIgnoreCase", sys_Str_compareIgnoreCase);
    fr_registerMethod(vm, "sys_Str_hash", sys_Str_hash);
    fr_registerMethod(vm, "sys_Str_toStr", sys_Str_toStr);
    fr_registerMethod(vm, "sys_Str_toLocale", sys_Str_toLocale);
    fr_registerMethod(vm, "sys_Str_isEmpty", sys_Str_isEmpty);
    fr_registerMethod(vm, "sys_Str_size", sys_Str_size);
    fr_registerMethod(vm, "sys_Str_intern", sys_Str_intern);
    fr_registerMethod(vm, "sys_Str_startsWith", sys_Str_startsWith);
    fr_registerMethod(vm, "sys_Str_endsWith", sys_Str_endsWith);
    fr_registerMethod(vm, "sys_Str_index", sys_Str_index);
    fr_registerMethod(vm, "sys_Str_indexr", sys_Str_indexr);
    fr_registerMethod(vm, "sys_Str_indexIgnoreCase", sys_Str_indexIgnoreCase);
    fr_registerMethod(vm, "sys_Str_indexrIgnoreCase", sys_Str_indexrIgnoreCase);
    fr_registerMethod(vm, "sys_Str_contains", sys_Str_contains);
    fr_registerMethod(vm, "sys_Str_containsChar", sys_Str_containsChar);
    fr_registerMethod(vm, "sys_Str_get", sys_Str_get);
    fr_registerMethod(vm, "sys_Str_getSafe", sys_Str_getSafe);
    fr_registerMethod(vm, "sys_Str_getRange", sys_Str_getRange);
    fr_registerMethod(vm, "sys_Str_plus", sys_Str_plus);
    fr_registerMethod(vm, "sys_Str_chars", sys_Str_chars);
    fr_registerMethod(vm, "sys_Str_each", sys_Str_each);
    fr_registerMethod(vm, "sys_Str_eachr", sys_Str_eachr);
    fr_registerMethod(vm, "sys_Str_any", sys_Str_any);
    fr_registerMethod(vm, "sys_Str_all", sys_Str_all);
    fr_registerMethod(vm, "sys_Str_spaces", sys_Str_spaces);
    fr_registerMethod(vm, "sys_Str_lower", sys_Str_lower);
    fr_registerMethod(vm, "sys_Str_upper", sys_Str_upper);
    fr_registerMethod(vm, "sys_Str_capitalize", sys_Str_capitalize);
    fr_registerMethod(vm, "sys_Str_decapitalize", sys_Str_decapitalize);
    fr_registerMethod(vm, "sys_Str_toDisplayName", sys_Str_toDisplayName);
    fr_registerMethod(vm, "sys_Str_fromDisplayName", sys_Str_fromDisplayName);
    fr_registerMethod(vm, "sys_Str_justl", sys_Str_justl);
    fr_registerMethod(vm, "sys_Str_justr", sys_Str_justr);
    fr_registerMethod(vm, "sys_Str_padl", sys_Str_padl);
    fr_registerMethod(vm, "sys_Str_padr", sys_Str_padr);
    fr_registerMethod(vm, "sys_Str_reverse", sys_Str_reverse);
    fr_registerMethod(vm, "sys_Str_trim", sys_Str_trim);
    fr_registerMethod(vm, "sys_Str_trimToNull", sys_Str_trimToNull);
    fr_registerMethod(vm, "sys_Str_trimStart", sys_Str_trimStart);
    fr_registerMethod(vm, "sys_Str_trimEnd", sys_Str_trimEnd);
    fr_registerMethod(vm, "sys_Str_split", sys_Str_split);
    fr_registerMethod(vm, "sys_Str_splitLines", sys_Str_splitLines);
    fr_registerMethod(vm, "sys_Str_replace", sys_Str_replace);
    fr_registerMethod(vm, "sys_Str_numNewlines", sys_Str_numNewlines);
    fr_registerMethod(vm, "sys_Str_isAscii", sys_Str_isAscii);
    fr_registerMethod(vm, "sys_Str_isSpace", sys_Str_isSpace);
    fr_registerMethod(vm, "sys_Str_isUpper", sys_Str_isUpper);
    fr_registerMethod(vm, "sys_Str_isLower", sys_Str_isLower);
    fr_registerMethod(vm, "sys_Str_isAlpha", sys_Str_isAlpha);
    fr_registerMethod(vm, "sys_Str_isAlphaNum", sys_Str_isAlphaNum);
    fr_registerMethod(vm, "sys_Str_localeCompare", sys_Str_localeCompare);
    fr_registerMethod(vm, "sys_Str_localeLower", sys_Str_localeLower);
    fr_registerMethod(vm, "sys_Str_localeUpper", sys_Str_localeUpper);
    fr_registerMethod(vm, "sys_Str_localeCapitalize", sys_Str_localeCapitalize);
    fr_registerMethod(vm, "sys_Str_localeDecapitalize", sys_Str_localeDecapitalize);
    fr_registerMethod(vm, "sys_Str_toBool", sys_Str_toBool);
    fr_registerMethod(vm, "sys_Str_toInt", sys_Str_toInt);
    fr_registerMethod(vm, "sys_Str_toFloat", sys_Str_toFloat);
    fr_registerMethod(vm, "sys_Str_toCode", sys_Str_toCode);
    fr_registerMethod(vm, "sys_Str_toXml", sys_Str_toXml);
    fr_registerMethod(vm, "sys_Str_finalize", sys_Str_finalize);
    fr_registerMethod(vm, "sys_Str_static$init", sys_Str_static__init);
    fr_registerMethod(vm, "sys_StrBuf__allocSize__", (fr_NativeFunc)sys_StrBuf__allocSize__);
    fr_registerMethod(vm, "sys_StrBuf_static$init", (fr_NativeFunc)sys_StrBuf_static__init);
    fr_registerMethod(vm, "sys_StrBuf_make", sys_StrBuf_make);
    fr_registerMethod(vm, "sys_StrBuf_isEmpty", sys_StrBuf_isEmpty);
    fr_registerMethod(vm, "sys_StrBuf_size", sys_StrBuf_size);
    fr_registerMethod(vm, "sys_StrBuf_capacity", sys_StrBuf_capacity);
    fr_registerMethod(vm, "sys_StrBuf_capacity", sys_StrBuf_capacity_);
    fr_registerMethod(vm, "sys_StrBuf_get", sys_StrBuf_get);
    fr_registerMethod(vm, "sys_StrBuf_getRange", sys_StrBuf_getRange);
    fr_registerMethod(vm, "sys_StrBuf_set", sys_StrBuf_set);
    fr_registerMethod(vm, "sys_StrBuf_add", sys_StrBuf_add);
    fr_registerMethod(vm, "sys_StrBuf_addChar", sys_StrBuf_addChar);
    fr_registerMethod(vm, "sys_StrBuf_join", sys_StrBuf_join);
    fr_registerMethod(vm, "sys_StrBuf_insert", sys_StrBuf_insert);
    fr_registerMethod(vm, "sys_StrBuf_remove", sys_StrBuf_remove);
    fr_registerMethod(vm, "sys_StrBuf_removeRange", sys_StrBuf_removeRange);
    fr_registerMethod(vm, "sys_StrBuf_replaceRange", sys_StrBuf_replaceRange);
    fr_registerMethod(vm, "sys_StrBuf_clear", sys_StrBuf_clear);
    fr_registerMethod(vm, "sys_StrBuf_toStr", sys_StrBuf_toStr);
    fr_registerMethod(vm, "sys_StrBuf_finalize", sys_StrBuf_finalize);
    fr_registerMethod(vm, "sys_This__allocSize__", (fr_NativeFunc)sys_This__allocSize__);
    fr_registerMethod(vm, "sys_This_static$init", (fr_NativeFunc)sys_This_static__init);
    fr_registerMethod(vm, "sys_This_make", sys_This_make);
    fr_registerMethod(vm, "sys_Void__allocSize__", (fr_NativeFunc)sys_Void__allocSize__);
    fr_registerMethod(vm, "sys_Void_static$init", (fr_NativeFunc)sys_Void_static__init);
    fr_registerMethod(vm, "sys_Void_make", sys_Void_make);
    fr_registerMethod(vm, "sys_ByteArray__allocSize__", (fr_NativeFunc)sys_ByteArray__allocSize__);
    fr_registerMethod(vm, "sys_ByteArray_static$init", (fr_NativeFunc)sys_ByteArray_static__init);
    fr_registerMethod(vm, "sys_ByteArray_make", sys_ByteArray_make);
    fr_registerMethod(vm, "sys_ByteArray_get", sys_ByteArray_get);
    fr_registerMethod(vm, "sys_ByteArray_set", sys_ByteArray_set);
    fr_registerMethod(vm, "sys_ByteArray_size", sys_ByteArray_size);
    fr_registerMethod(vm, "sys_ByteArray_realloc", sys_ByteArray_realloc);
    fr_registerMethod(vm, "sys_ByteArray_copyFrom", sys_ByteArray_copyFrom);
    fr_registerMethod(vm, "sys_ByteArray_finalize", sys_ByteArray_finalize);
    fr_registerMethod(vm, "sys_IntArray__allocSize__", (fr_NativeFunc)sys_IntArray__allocSize__);
    fr_registerMethod(vm, "sys_IntArray_static$init", (fr_NativeFunc)sys_IntArray_static__init);
    fr_registerMethod(vm, "sys_IntArray_make", sys_IntArray_make);
    fr_registerMethod(vm, "sys_IntArray_get", sys_IntArray_get);
    fr_registerMethod(vm, "sys_IntArray_set", sys_IntArray_set);
    fr_registerMethod(vm, "sys_IntArray_size", sys_IntArray_size);
    fr_registerMethod(vm, "sys_IntArray_realloc", sys_IntArray_realloc);
    fr_registerMethod(vm, "sys_IntArray_copyFrom", sys_IntArray_copyFrom);
    fr_registerMethod(vm, "sys_IntArray_finalize", sys_IntArray_finalize);
    fr_registerMethod(vm, "sys_ObjArray__allocSize__", (fr_NativeFunc)sys_ObjArray__allocSize__);
    fr_registerMethod(vm, "sys_ObjArray_static$init", (fr_NativeFunc)sys_ObjArray_static__init);
    fr_registerMethod(vm, "sys_ObjArray_make", sys_ObjArray_make);
    fr_registerMethod(vm, "sys_ObjArray_get", sys_ObjArray_get);
    fr_registerMethod(vm, "sys_ObjArray_set", sys_ObjArray_set);
    fr_registerMethod(vm, "sys_ObjArray_size", sys_ObjArray_size);
    fr_registerMethod(vm, "sys_ObjArray_realloc", sys_ObjArray_realloc);
    fr_registerMethod(vm, "sys_ObjArray_copyFrom", sys_ObjArray_copyFrom);
    fr_registerMethod(vm, "sys_ObjArray_finalize", sys_ObjArray_finalize);
    fr_registerMethod(vm, "sys_Slot__allocSize__", (fr_NativeFunc)sys_Slot__allocSize__);
    fr_registerMethod(vm, "sys_Slot_static$init", (fr_NativeFunc)sys_Slot_static__init);
    fr_registerMethod(vm, "sys_Slot_find", sys_Slot_find);
    fr_registerMethod(vm, "sys_Slot_findMethod", sys_Slot_findMethod);
    fr_registerMethod(vm, "sys_Slot_findField", sys_Slot_findField);
    fr_registerMethod(vm, "sys_Slot_findFunc", sys_Slot_findFunc);
    fr_registerMethod(vm, "sys_Slot_make", sys_Slot_make);
    fr_registerMethod(vm, "sys_Slot_parent", sys_Slot_parent);
    fr_registerMethod(vm, "sys_Slot_name", sys_Slot_name);
    fr_registerMethod(vm, "sys_Slot_qname", sys_Slot_qname);
    fr_registerMethod(vm, "sys_Slot_isField", sys_Slot_isField);
    fr_registerMethod(vm, "sys_Slot_isMethod", sys_Slot_isMethod);
    fr_registerMethod(vm, "sys_Slot_isAbstract", sys_Slot_isAbstract);
    fr_registerMethod(vm, "sys_Slot_isConst", sys_Slot_isConst);
    fr_registerMethod(vm, "sys_Slot_isCtor", sys_Slot_isCtor);
    fr_registerMethod(vm, "sys_Slot_isInternal", sys_Slot_isInternal);
    fr_registerMethod(vm, "sys_Slot_isNative", sys_Slot_isNative);
    fr_registerMethod(vm, "sys_Slot_isOverride", sys_Slot_isOverride);
    fr_registerMethod(vm, "sys_Slot_isPrivate", sys_Slot_isPrivate);
    fr_registerMethod(vm, "sys_Slot_isProtected", sys_Slot_isProtected);
    fr_registerMethod(vm, "sys_Slot_isPublic", sys_Slot_isPublic);
    fr_registerMethod(vm, "sys_Slot_isStatic", sys_Slot_isStatic);
    fr_registerMethod(vm, "sys_Slot_isSynthetic", sys_Slot_isSynthetic);
    fr_registerMethod(vm, "sys_Slot_isVirtual", sys_Slot_isVirtual);
    fr_registerMethod(vm, "sys_Slot_facets", sys_Slot_facets);
    fr_registerMethod(vm, "sys_Slot_facet", sys_Slot_facet);
    fr_registerMethod(vm, "sys_Slot_hasFacet", sys_Slot_hasFacet);
    fr_registerMethod(vm, "sys_Slot_doc", sys_Slot_doc);
    fr_registerMethod(vm, "sys_Slot_toStr", sys_Slot_toStr);
    fr_registerMethod(vm, "sys_Slot_signature", sys_Slot_signature);
    fr_registerMethod(vm, "sys_Field__allocSize__", (fr_NativeFunc)sys_Field__allocSize__);
    fr_registerMethod(vm, "sys_Field_static$init", (fr_NativeFunc)sys_Field_static__init);
    fr_registerMethod(vm, "sys_Field_makeSetFunc", sys_Field_makeSetFunc);
    fr_registerMethod(vm, "sys_Field_privateMake", sys_Field_privateMake);
    fr_registerMethod(vm, "sys_Field_type", sys_Field_type);
    fr_registerMethod(vm, "sys_Field_get", sys_Field_get);
    fr_registerMethod(vm, "sys_Field_set", sys_Field_set);
    fr_registerMethod(vm, "sys_Field_make", sys_Field_make);
    fr_registerMethod(vm, "sys_Func__allocSize__", (fr_NativeFunc)sys_Func__allocSize__);
    fr_registerMethod(vm, "sys_Func_static$init", (fr_NativeFunc)sys_Func_static__init);
    fr_registerMethod(vm, "sys_Func_make", sys_Func_make);
    fr_registerMethod(vm, "sys_Func_returns", sys_Func_returns);
    fr_registerMethod(vm, "sys_Func_arity", sys_Func_arity);
    fr_registerMethod(vm, "sys_Func_params", sys_Func_params);
    fr_registerMethod(vm, "sys_Func_method", sys_Func_method);
    fr_registerMethod(vm, "sys_Func_callList", sys_Func_callList);
    fr_registerMethod(vm, "sys_Func_callOn", sys_Func_callOn);
    fr_registerMethod(vm, "sys_Func_call", sys_Func_call);
    fr_registerMethod(vm, "sys_Func_bind", sys_Func_bind);
    fr_registerMethod(vm, "sys_Func_retype", sys_Func_retype);
    fr_registerMethod(vm, "sys_Func_enterCtor", sys_Func_enterCtor);
    fr_registerMethod(vm, "sys_Func_exitCtor", sys_Func_exitCtor);
    fr_registerMethod(vm, "sys_Method__allocSize__", (fr_NativeFunc)sys_Method__allocSize__);
    fr_registerMethod(vm, "sys_Method_static$init", (fr_NativeFunc)sys_Method_static__init);
    fr_registerMethod(vm, "sys_Method_privateMake", sys_Method_privateMake);
    fr_registerMethod(vm, "sys_Method_returns", sys_Method_returns);
    fr_registerMethod(vm, "sys_Method_params", sys_Method_params);
    fr_registerMethod(vm, "sys_Method_func", sys_Method_func);
    fr_registerMethod(vm, "sys_Method_callList", sys_Method_callList);
    fr_registerMethod(vm, "sys_Method_callOn", sys_Method_callOn);
    fr_registerMethod(vm, "sys_Method_call", sys_Method_call);
    fr_registerMethod(vm, "sys_Method_make", sys_Method_make);
    fr_registerMethod(vm, "sys_Param__allocSize__", (fr_NativeFunc)sys_Param__allocSize__);
    fr_registerMethod(vm, "sys_Param_static$init", (fr_NativeFunc)sys_Param_static__init);
    fr_registerMethod(vm, "sys_Param_make", sys_Param_make);
    fr_registerMethod(vm, "sys_Param_name", sys_Param_name);
    fr_registerMethod(vm, "sys_Param_type", sys_Param_type);
    fr_registerMethod(vm, "sys_Param_hasDefault", sys_Param_hasDefault);
    fr_registerMethod(vm, "sys_Param_toStr", sys_Param_toStr);
    fr_registerMethod(vm, "sys_Pod__allocSize__", (fr_NativeFunc)sys_Pod__allocSize__);
    fr_registerMethod(vm, "sys_Pod_static$init", (fr_NativeFunc)sys_Pod_static__init);
    fr_registerMethod(vm, "sys_Pod_of", sys_Pod_of);
    fr_registerMethod(vm, "sys_Pod_list", sys_Pod_list);
    fr_registerMethod(vm, "sys_Pod_find", sys_Pod_find);
    fr_registerMethod(vm, "sys_Pod_load", sys_Pod_load);
    fr_registerMethod(vm, "sys_Pod_make", sys_Pod_make);
    fr_registerMethod(vm, "sys_Pod_name", sys_Pod_name);
    fr_registerMethod(vm, "sys_Pod_version", sys_Pod_version);
    fr_registerMethod(vm, "sys_Pod_depends", sys_Pod_depends);
    fr_registerMethod(vm, "sys_Pod_uri", sys_Pod_uri);
    fr_registerMethod(vm, "sys_Pod_toStr", sys_Pod_toStr);
    fr_registerMethod(vm, "sys_Pod_meta", sys_Pod_meta);
    fr_registerMethod(vm, "sys_Pod_types", sys_Pod_types);
    fr_registerMethod(vm, "sys_Pod_type", sys_Pod_type);
    fr_registerMethod(vm, "sys_Pod_files", sys_Pod_files);
    fr_registerMethod(vm, "sys_Pod_file", sys_Pod_file);
    fr_registerMethod(vm, "sys_Pod_doc", sys_Pod_doc);
    fr_registerMethod(vm, "sys_Pod_log", sys_Pod_log);
    fr_registerMethod(vm, "sys_Pod_props", sys_Pod_props);
    fr_registerMethod(vm, "sys_Pod_config", sys_Pod_config);
    fr_registerMethod(vm, "sys_Pod_locale", sys_Pod_locale);
    fr_registerMethod(vm, "sys_Type__allocSize__", (fr_NativeFunc)sys_Type__allocSize__);
    fr_registerMethod(vm, "sys_Type_static$init", (fr_NativeFunc)sys_Type_static__init);
    fr_registerMethod(vm, "sys_Type_privateMake", sys_Type_privateMake);
    fr_registerMethod(vm, "sys_Type_of", sys_Type_of);
    fr_registerMethod(vm, "sys_Type_find", sys_Type_find);
    fr_registerMethod(vm, "sys_Type_pod", sys_Type_pod);
    fr_registerMethod(vm, "sys_Type_name", sys_Type_name);
    fr_registerMethod(vm, "sys_Type_qname", sys_Type_qname);
    fr_registerMethod(vm, "sys_Type_signature", sys_Type_signature);
    fr_registerMethod(vm, "sys_Type_base", sys_Type_base);
    fr_registerMethod(vm, "sys_Type_mixins", sys_Type_mixins);
    fr_registerMethod(vm, "sys_Type_inheritance", sys_Type_inheritance);
    fr_registerMethod(vm, "sys_Type_fits", sys_Type_fits);
    fr_registerMethod(vm, "sys_Type_isVal", sys_Type_isVal);
    fr_registerMethod(vm, "sys_Type_isNullable", sys_Type_isNullable);
    fr_registerMethod(vm, "sys_Type_toNullable", sys_Type_toNullable);
    fr_registerMethod(vm, "sys_Type_toNonNullable", sys_Type_toNonNullable);
    fr_registerMethod(vm, "sys_Type_isGeneric", sys_Type_isGeneric);
    fr_registerMethod(vm, "sys_Type_params", sys_Type_params);
    fr_registerMethod(vm, "sys_Type_parameterize", sys_Type_parameterize);
    fr_registerMethod(vm, "sys_Type_toListOf", sys_Type_toListOf);
    fr_registerMethod(vm, "sys_Type_emptyList", sys_Type_emptyList);
    fr_registerMethod(vm, "sys_Type_isAbstract", sys_Type_isAbstract);
    fr_registerMethod(vm, "sys_Type_isClass", sys_Type_isClass);
    fr_registerMethod(vm, "sys_Type_isConst", sys_Type_isConst);
    fr_registerMethod(vm, "sys_Type_isEnum", sys_Type_isEnum);
    fr_registerMethod(vm, "sys_Type_isFacet", sys_Type_isFacet);
    fr_registerMethod(vm, "sys_Type_isFinal", sys_Type_isFinal);
    fr_registerMethod(vm, "sys_Type_isInternal", sys_Type_isInternal);
    fr_registerMethod(vm, "sys_Type_isMixin", sys_Type_isMixin);
    fr_registerMethod(vm, "sys_Type_isPublic", sys_Type_isPublic);
    fr_registerMethod(vm, "sys_Type_isSynthetic", sys_Type_isSynthetic);
    fr_registerMethod(vm, "sys_Type_fields", sys_Type_fields);
    fr_registerMethod(vm, "sys_Type_methods", sys_Type_methods);
    fr_registerMethod(vm, "sys_Type_slots", sys_Type_slots);
    fr_registerMethod(vm, "sys_Type_field", sys_Type_field);
    fr_registerMethod(vm, "sys_Type_method", sys_Type_method);
    fr_registerMethod(vm, "sys_Type_slot", sys_Type_slot);
    fr_registerMethod(vm, "sys_Type_make", sys_Type_make);
    fr_registerMethod(vm, "sys_Type_facets", sys_Type_facets);
    fr_registerMethod(vm, "sys_Type_facet", sys_Type_facet);
    fr_registerMethod(vm, "sys_Type_hasFacet", sys_Type_hasFacet);
    fr_registerMethod(vm, "sys_Type_doc", sys_Type_doc);
    fr_registerMethod(vm, "sys_Type_toStr", sys_Type_toStr);
    fr_registerMethod(vm, "sys_Type_toLocale", sys_Type_toLocale);
}
